import pyotp
import pyqrcode

from code_helper import checkTotp


def setupBot() -> True:
    telegramKey = input("Put you telegram key: ")

    key = pyotp.random_base32()
    uri = pyotp.totp.TOTP(key).provisioning_uri(name='Shelly Telegram Bot', issuer_name='')

    print("Put this code in const_private and in your totp generator app: " + key)
    print(pyqrcode.create(uri).terminal(quiet_zone=2))

    if checkTotp(input("Enter the code generated by your app: "), key):
        content = "TELEGRAM_TOKEN = \"" + telegramKey + "\"\n"
        content = content + "TOTP_KEY = \"" + key + "\"\n"

        with open("./const_private.py", "w") as file:
            file.write(content)
        return True
    else:
        print("Sorry the generated code is incorrect")
        return False
